=== JAlvarezGW19/CYBERSEGURIDAD/docs/schema_resultados.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Resultado de Auditoría - Seguridad Informática",
    "description": "Contrato de datos para los módulos de la suite de auditoría",
    "type": "object",
    "properties": {
        "modulo": {
            "type": "string",
            "description": "Nombre del módulo (ej: DNS, PortScanning, OSINT)"
        },
        "grupo": {
            "type": "integer",
            "minimum": 1,
            "maximum": 4
        },
        "estudiante": {
            "type": "string",
            "description": "Identificador del estudiante (ej: E1, E2)"
        },
        "target": {
            "type": "string",
            "description": "El objetivo analizado (IP o Dominio)"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "ISO 8601 de la ejecución"
        },
        "status": {
            "type": "string",
            "enum": [
                "success",
                "error"
            ]
        },
        "data": {
            "type": "object",
            "description": "Resultados técnicos específicos obtenidos por la función"
        },
        "error_message": {
            "type": [
                "string",
                "null"
            ],
            "description": "Detalle del error si status es 'error'"
        }
    },
    "required": [
        "modulo",
        "grupo",
        "estudiante",
        "target",
        "timestamp",
        "status",
        "data"
    ]
}

=== JAlvarezGW19/CYBERSEGURIDAD/historial_auditoria.json
[
    {
        "modulo": "OSINT",
        "grupo": 2,
        "estudiante": "E2",
        "target": "target.com",
        "timestamp": "2026-04-26T20:10:08.495531",
        "status": "success",
        "data": {
            "dork_utilizado": "site:*.target.com -www",
            "total_encontrados": 0,
            "subdominios": []
        },
        "error_message": null
    },
    {
        "modulo": "OSINT",
        "grupo": 2,
        "estudiante": "E3",
        "target": "target.com",
        "timestamp": "2026-04-26T20:10:09.065483",
        "status": "success",
        "data": {
            "total_encontrados": 0,
            "archivos_indexados": [],
            "nota": "B\u00fasqueda completada o interrumpida por rate-limit de Google."
        },
        "error_message": null
    },
    {
        "modulo": "Reconocimiento DNS",
        "grupo": 1,
        "estudiante": "E1",
        "target": "scanme.nmap.org",
        "timestamp": "2026-05-19T16:33:31.013432",
        "data": {
            "A": [
                "45.33.32.156"
            ],
            "AAAA": [
                "2600:3c01::f03c:91ff:fe18:bb2f"
            ]
        },
        "status": "success",
        "error_message": null
    },
    {
        "modulo": "Reconocimiento DNS",
        "grupo": 1,
        "estudiante": "E2",
        "target": "scanme.nmap.org",
        "timestamp": "2026-05-19T16:33:31.207231",
        "data": {
            "MX": [],
            "NS": []
        },
        "status": "success",
        "error_message": null
    },
    {
        "modulo": "Reconocimiento DNS",
        "grupo": 1,
        "estudiante": "E3",
        "target": "scanme.nmap.org",
        "timestamp": "2026-05-19T16:33:31.372224",
        "data": {
            "TXT": [],
            "SOA": []
        },
        "status": "success",
        "error_message": null
    },
    {
        "modulo": "Scanning",
        "grupo": 4,
        "estudiante": "E1",
        "target": "scanme.nmap.org",
        "timestamp": "2026-05-19T12:33:31.595623",
        "status": "success",
        "data": {
            "puertos_escaneados": [
                22,
                80,
                443
            ],
            "detalles": [
                {
                    "puerto": 22,
                    "estado": "abierto",
                    "protocolo": "TCP"
                },
                {
                    "puerto": 80,
                    "estado": "abierto",
                    "protocolo": "TCP"
                },
                {
                    "puerto": 443,
                    "estado": "cerrado",
                    "protocolo": "TCP"
                }
            ]
        },
        "error_message": null
    },
    {
        "modulo": "Enumeracion SMB",
        "grupo": 2,
        "estudiante": "E1/E3",
        "target": "127.0.0.1",
        "timestamp": "2026-05-29T20:19:52.498208",
        "status": "success",
        "data": {
            "port": 445,
            "null_session_established": false,
            "shares": [],
            "users": [],
            "credenciales_encontradas": []
        },
        "error_message": "La librer\u00eda pysmb no est\u00e1 instalada. Ejecute: pip install pysmb"
    },
    {
        "modulo": "Enumeracion SMB",
        "grupo": 2,
        "estudiante": "E1/E3",
        "target": "127.0.0.1",
        "timestamp": "2026-05-29T20:20:31.271480",
        "status": "success",
        "data": {
            "port": 445,
            "null_session_established": false,
            "shares": [],
            "users": [],
            "credenciales_encontradas": []
        },
        "error_message": "La librer\u00eda pysmb no est\u00e1 instalada. Ejecute: pip install pysmb"
    },
    {
        "modulo": "Enumeracion SMB",
        "grupo": 2,
        "estudiante": "E1/E2/E3",
        "target": "127.0.0.1",
        "timestamp": "2026-06-07T12:30:24.174794",
        "status": "success",
        "data": {
            "port": 445,
            "null_session_established": false,
            "shares": [],
            "users": [],
            "credenciales_encontradas": []
        },
        "error_message": null
    }
]
